# Generated by Django 5.2.12 on 2026-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fournisseur", models.CharField(max_length=255)),
                ("date_facture", models.DateField(blank=True, null=True)),
                ("total_ttc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("devise", models.CharField(default="EUR", max_length=10)),
                ("fichier_pdf", models.FileField(upload_to="factures_archive/")),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
