# Generated by Django 5.2.12 on 2026-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_invoice_delete_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(default='Divers', max_length=100),
        ),
    ]
